CFLAGS = -O0 -fno-stack-protector -no-pie -fno-pie -fno-omit-frame-pointer -ggdb

all: challenge16

challenge16: challenge16.c
	gcc $(CFLAGS) -static challenge16.c -o challenge16

clean:
	rm challenge16

