all: stack intra_chunk inter_chunk

stack: stack.c
	gcc stack.c -o stack

intra_chunk: intra_chunk.c
	gcc intra_chunk.c -o intra_chunk -O

inter_chunk: inter_chunk.c
	gcc inter_chunk.c -o inter_chunk
